print ("My name is June Caldonia Seever")
print ("I am 13 years old")
input ()
print ("This class is lowkey fun lol")
print ("i like coding in little faces!")
name = input("would you like to see?")
print(f"im glad you said {name}! hit enter to see them!")
input ()
print ("(• ε •)")
print ("ʕ•ᴥ•ʔ <---- aww such a cute bearr")
print ("( ━☞´◔‿ゝ◔`)━☞ <----- this ones one of my favorites!!!")
input ()
print ("ok time to get back to facts :(")
input ()
print ("i have a little dog named fern! oᴥo")
print ("shes so cute!")
print ("any how,")
print ("this is my 6th school! isnt that crazy!")
print ("kk byeeeeeeeeeeeeeeeeeeeyeeeeeee")