print ("why did the chicken cross the road")
input ()
print ("to get to the other side")
input ()
print ("u should laugh now")
input ()
print ("haha")
input ()
print ("want another joke?")
input ()
print ("the only other joke here is your face")
print ("...")
input ()
print ("haha no get rickrolled")
print ("( ━☞´◔‿ゝ◔`)━☞")
